BEGIN;

CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions;
SET LOCAL timezone = 'America/Sao_Paulo';

SELECT plan(12);

SELECT has_trigger('public', 'payout_monthly_closings', 'guard_payout_closing_month',
  'closings have the month lock');
SELECT ok(
  NOT has_function_privilege('anon', 'eon_private.guard_payout_closing_month()', 'EXECUTE')
  AND NOT has_function_privilege('authenticated', 'eon_private.guard_payout_closing_month()', 'EXECUTE'),
  'the lock function is not exposed'
);

-- Meses relativos à data de Brasília. Os fechamentos de verdade ficam de fora:
-- a tabela é limpa só dentro desta transação.
DELETE FROM public.payout_pending_repasse;
DELETE FROM public.payout_monthly_closings;

CREATE TEMP TABLE lock_months ON COMMIT DROP AS
SELECT date_trunc('month', now() AT TIME ZONE 'America/Sao_Paulo')::date AS current_month;

-- Gerar -----------------------------------------------------------------------

SELECT throws_ok(
  $$INSERT INTO public.payout_monthly_closings (competence, status)
    SELECT current_month, 'pending_approval' FROM lock_months$$,
  '23514', NULL,
  'the current month cannot be closed'
);
SELECT throws_ok(
  $$INSERT INTO public.payout_monthly_closings (competence, status)
    SELECT (current_month + interval '1 month')::date, 'pending_approval' FROM lock_months$$,
  '23514', NULL,
  'a future month cannot be closed'
);
SELECT throws_ok(
  $$INSERT INTO public.payout_monthly_closings (competence, status) VALUES ('2999-12-01', 'pending_approval')$$,
  '23514',
  'Dezembro de 2999 ainda não terminou. O fechamento fica disponível a partir de 01/01/3000.',
  'the message names the month and the first allowed day'
);
SELECT lives_ok(
  $$INSERT INTO public.payout_monthly_closings (competence, status)
    SELECT (current_month - interval '1 month')::date, 'pending_approval' FROM lock_months$$,
  'the month that just ended can be closed'
);

-- Aprovar e trocar a data -----------------------------------------------------

SELECT lives_ok(
  $$UPDATE public.payout_monthly_closings SET status = 'approved'
    WHERE competence = (SELECT (current_month - interval '1 month')::date FROM lock_months)$$,
  'an ended month can be approved'
);
SELECT throws_ok(
  $$UPDATE public.payout_monthly_closings SET competence = (SELECT current_month FROM lock_months)
    WHERE competence = (SELECT (current_month - interval '1 month')::date FROM lock_months)$$,
  '23514', NULL,
  'a closing cannot be moved into the current month'
);

-- Fechamento do mês atual que já existia antes da trava -----------------------

ALTER TABLE public.payout_monthly_closings DISABLE TRIGGER guard_payout_closing_month;
INSERT INTO public.payout_monthly_closings (competence, status)
SELECT current_month, 'pending_approval' FROM lock_months;
ALTER TABLE public.payout_monthly_closings ENABLE TRIGGER guard_payout_closing_month;

SELECT throws_ok(
  $$UPDATE public.payout_monthly_closings SET status = 'approved'
    WHERE competence = (SELECT current_month FROM lock_months)$$,
  '23514', NULL,
  'a closing of the current month cannot be approved'
);
SELECT lives_ok(
  $$UPDATE public.payout_monthly_closings SET generated_at = now()
    WHERE competence = (SELECT current_month FROM lock_months)$$,
  'touching other columns does not trip the lock'
);
SELECT lives_ok(
  $$DELETE FROM public.payout_monthly_closings
    WHERE competence = (SELECT current_month FROM lock_months)$$,
  'a closing generated by mistake can still be deleted'
);
SELECT is(
  (SELECT count(*)::int FROM public.payout_monthly_closings),
  1,
  'only the closing of the ended month is left'
);

SELECT * FROM finish();
ROLLBACK;
